export const teamDatabase = [
  { teamName: "Team Apex", password: "apex321" },
  { teamName: "Kasayie", password: "kasayie987" },
  { teamName: "Twilight", password: "twilight789" },
  { teamName: "DevForChange(DFC)", password: "dfc987" },
  { teamName: "Team WRAPE", password: "wrape789" },
  { teamName: "Wiemo team", password: "wiemo987" },
  { teamName: "GONGO TECH", password: "gongo123" },
  { teamName: "Team Kasa Nimdie", password: "kasa456" },
  { teamName: "Yerekasa", password: "yerekasa789" },
  { teamName: "Team EchoVoice", password: "echo456" },
  { teamName: "HandWave", password: "wave321" },
  { teamName: "SproutAI", password: "sprout456" },
  { teamName: "WhisperWave", password: "whisper789" },
  { teamName: "KASA NOMA", password: "noma654" },
  { teamName: "Admin", password: "admin789" },
  { teamName: "TwiTalk", password: "twitalk123" },
  { teamName: "KasaYie", password: "kasayie123" },
  { teamName: "YADAH", password: "yadah654" },
  { teamName: "Voice Craft AI", password: "craft654" },
];
